### PR TITLE
CI with GitHub Actions

### PR DESCRIPTION
**Pull request by chris-martin**
The build matrix tests all the supported GHC versions, based on the supported versions of `base` given in the cabal file.

I like to test with cabal file for each build so that I can put in constraints to ensure that the CI is testing as many versions that the cabal file declares to be in bounds as possible. I haven't done that very much here, but I have put in constraints for the oldest build to test minimum bounds. The second commit raises the minimum bounds to reflect what is actually testable with GHC 7.10. Anyway, those are just my preferences, but thought I'd offer.

### CODE REVIEW

**Review by Gabriel439 — COMMENTED** [review]
I'd suggest only testing GHC 8.10 and later (and updating `pipes-safe.cabal`'s `Tested-With` section to match).  This is mainly so that CI is bottlenecked on waiting for available builders or on waiting for older/slower GHC's to build things

**Comment by chris-martin** [comment]
Should raise the `base` lower bound accordingly?

**Comment by Gabriel439** [comment]
Yeah, that would be good to do, too

**Comment by chris-martin** [comment]
Updated. Minimum GHC lower bound is 8.10. With the other dependency bounds raised accordingly, all CPP and cabal conditionals are now obviated.

**Pull request merged**
